name: Linters and Tests

on: [pull_request]

permissions:
  contents: 'read'
  pull-requests: 'read'
  packages: 'read'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: make this-ci

